language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: OFYTyNgaGOEpHtGpDErHmc2EDOUCLmfGeeTEsbcl5ICw1eWoT30TfH6lmdfBlu9oltECE5P93StvZmL9o284hyJxtlutNTIbJ2WmimAnlnjuo506sjO8V8Qf++W5j4cLqZzn8z7q/h8p0uWUGXeRAkZPU3m4l5lNkMwQo74HyJrifaYRQX+YdPY636qMitO6y6VZXLioOimG2J8yGvd/izzF7ee0UtEl8LUqh+IZsOyuuLjUSnytXCebAQYJTmVVHVtEdQbZF74leQ8yYttiz0bXhJOsJDGvSDm/jnZpqLn4rypQscO8wCPj+nZBpxj7nOT9jhldLVhdfOnbzUHwhWLBCSg4to6nUWwEZJ7uE7FYxYF6yr16tFtvl1VVuETVnsgYTnx4DagCRePOoqYAmydeMjhznOrpl/gCZn9Od8M/DiwDQJ/05zVMS0RZD8CgnZqpF+LA4qvXobapOh6/owUqCQcfUWuAB7arClvnpGi34CJ2cXBj3vOWJ6LmxYRV3q6XV5ZHMConziz6wo6sDxDNAwI3Rwm7pqUYf1gaMx9Bi4ypRgsdqw0N6EnnNDq+l11kIbjwwBGHYusVl9S3OYScPCcYmRxPwwLEzlj6GGmHYIe2VW0ClMHTMOp/uXEOeYMrIqJE/bIcOgTTXsPNWx2kGGWMPEc0ks3jQtXPAvA=
  app: node-shopping-list-integration-tests
  on:
    repo: joncancode/node-shopping-list-integration-tests
